{
  "runtime": 507,
  "percentageScore": 100,
  "count": {
    "total": 2,
    "passed": 2
  },
  "failedTestCases": [],
  "suites": [
    {
      "suiteName": "GET /test-custome-error",
      "passed": true,
      "testCases": [
        {
          "passed": true,
          "description": "The response should be 'testing app-level custom error handling middleware,' as we intentionally threw this custom error with a status code of 505"
        }
      ]
    },
    {
      "suiteName": "GET /test-unhandled-error",
      "passed": true,
      "testCases": [
        {
          "passed": true,
          "description": "Testing unhandled errors must trigger a '500' Internal Server Error with the message 'oops! something went wrong...Try again later!"
        }
      ]
    }
  ]
}